"""Generate runtime graph identities from independently decoded source packages."""
import argparse
import json
from pathlib import Path

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("manifest", type=Path)
parser.add_argument("variants", type=Path)
parser.add_argument("output", type=Path)
parser.add_argument("readbacks", type=Path, nargs="+")
args = parser.parse_args()
if args.output.exists():
    raise FileExistsError(args.output)
roots = {}
for path in args.readbacks:
    for exports in json.loads(path.read_text()).values():
        for entry in exports:
            if entry["Type"] == "Material":
                root = {key: entry[key] for key in ("Properties", "CachedExpressionData")}
                if entry["Package"] in roots and roots[entry["Package"]] != root:
                    raise ValueError("Conflicting root readbacks")
                roots[entry["Package"]] = root
manifest = json.loads(args.manifest.read_text())["materials"]
variants = {entry["parent"]: entry for entry in json.loads(args.variants.read_text())["materials"]}
native = {
    "M_Genessa_eye": ("/Game/Sparta/FX/VFX/Shells/Genessa/Eyes/Materials/M_Genessa_Eyes", "eye"),
    "M_Genessa_smoke": ("/Game/Sparta/FX/VFX/Shells/Genessa/Eyes/Materials/M_Genessa_Eyes_Smoke", "smoke"),
    "M_EyeRefraction": ("/Game/Sparta/MasterMaterials/Character_Materials/Eyes/Shared/M_refraction_01", "refraction"),
    "M_Uber_opaque": ("/Game/Sparta/MasterMaterials/Character_Materials/UberShaderV2/M_Uber", "uber"),
}
rows = []
seen_roots = set()
for spec in manifest:
    if spec["name"] == "M_Uber_masked":
        continue
    root, family = native.get(spec["name"], (spec.get("source_parent"), "authored"))
    if root in seen_roots:
        raise ValueError("Duplicate source material root")
    seen_roots.add(root)
    entry = roots[root]
    properties, cached = entry["Properties"], entry["CachedExpressionData"]
    state_id = properties["StateId"].split("-")
    if len(state_id) != 4 or any(len(word) != 8 for word in state_id):
        raise ValueError("Unexpected UE GUID encoding")
    for word in state_id:
        int(word, 16)
    blend_name = properties.get("BlendMode", "BLEND_Opaque").rsplit("::", 1)[-1]
    blend = {"BLEND_Opaque": 0, "BLEND_Masked": 1, "BLEND_Translucent": 2,
             "BLEND_TranslucentGreyTransmittance": 2}[blend_name]
    switches = []
    for info, value in zip(cached["RuntimeEntries[8]"]["ParameterInfoSet"], cached["StaticSwitchValues"], strict=True):
        if info["Association"].rsplit("::", 1)[-1] != "GlobalParameter" or info["Index"] != -1:
            raise ValueError("Unexpected root switch association")
        switches.append("{" + json.dumps(info["Name"]) + "," + str(value).lower() + "}")
    variant = variants[spec["material"]]
    root_object = root + "." + root.rsplit("/", 1)[-1]
    values = [json.dumps(root_object), json.dumps(spec["material"]), json.dumps(variant["variant"]),
              "{" + ",".join("0x" + word + "u" for word in state_id) + "}",
              "AstralMaterialFamily::" + family, str(blend), str(variant["parent_two_sided"]).lower(),
              repr(properties.get("OpacityMaskClipValue", .3333)) + "f", "{" + ",".join(switches) + "}"]
    rows.append("    {" + ",\n     ".join(values) + "}")
if len(rows) != len(manifest) - 1 or len(rows) < 11:
    raise ValueError("Expected all root graphs except the alternate Uber masked companion")
args.output.write_text("// Generated by tools/shared-assets/generate-adapter-catalog.py from cooked source readbacks.\n"
    f"static const std::array<AstralMaterialDefinition,{len(rows)}> astral_material_definitions{{{{\n"
    + ",\n".join(rows) + "\n}};\n")
